### PR TITLE
Figure output for web 

### PR DESCRIPTION
**Pull request by fvalka**
## Necessary changes to your repo for making it work
- Create a Token which can be used to push to the gh-pages branch and store it as a Secret in the repositories settings under the name GH_PAGES_ACCESS_TOKEN

### Secrets/Token Set-Up
image

## Execution of the model run/workflow
The workflow can be started in two different ways:
- Manually by executing a GitHub API call, this is described in .github/workflows/run-model-and-publish.yml
- Triggering the workflow only works on the master branch

## Changes to the R base code
- I've added additional plot exports to both the three-panel plots and the forecast. Those are used to export both a mobile and desktop version of each figure. 
- Each figure from the three-panel plots is a separate figure and file. 
- I've removed the Forecast label on the forecast since this was also not shown correctly in the PDF and seems to have been a mistake left in there 
- base.R I've added a mechanism similar to the one used for DEBUG, where either an environment variable can be set or inside the code to use the full number of iterations. The README.md has been changed accordingly. 
- Calculation of N2 based upon 75 + the difference between the ECDC data date and the original reports data date

## Font-workaround
The SVG output in the Docker image creates an invalid font-name "Aerial". I've searched the source code of the R libraries used and found no reference to it. 
- To work around this a new R file has been added: "web-fix-fonts.R", which replaces "Aerial" in the SVG files with a whole font family, making it more robust in addition to fixing this mistake. 

**Changes to the current CI pipeline and Dockerimage**
- I've changed the ENTRYPOINT to a CMD, so that the Dockerimage can also be used correctly with other commands in run
- I've removed the scripts which change the uid and guid and instead used the --user flag of docker run
- The current workflow/CI-pipeline has been adjusted accordingly 

## New workflow
- The new GitHub actions workflow performs a couple of steps for generating the GitHub pages each day:
 - Git clone
 - Build the docker image, as in the CI pipeline
 - Download the newest ECDC data
 - Perform a full model run, set by setting --env FULL=TRUE
 - Apply the font-workaround described above
 - Publish the web subfolder to the new private repository where it can be manually verified and then published later.

### CODE REVIEW

**Comment by harrisonzhu508** [comment]
This looks good to me.

**Comment by s-mishra** [comment]
We should change this a bit by not running on github machines but a self-hosted server. We need to get that in the CD script now and also I think currently we are pushing web directory after run but that directory doesn't exist on covid19estimates. We will need to change this to make sure we output in the correct folder.

**Comment by fvalka** [comment]
Working on it to get to run on Azure. The web folder part is correct, it tells the deploy GitHub action which subfolder to us as it's root folder when committing and pushing into the other repo, I've tested it yesterday from my fork and it pushes it correctly into the master of covid19estimates, keeping the current files and only replacing new files.

**Comment by harrisonzhu508** [comment]
Thanks, that's great. Where is the HTML code for the website by the way, currently? @fvalka

**Comment by fvalka** [comment]
@harrisonzhu508 in the private covid19estimates repo, under the ImperialCollegeLondon user, you should have access there, otherwise @s-mishra can surely give it to you :-)

**Comment by s-mishra** [comment]
@harrisonzhu508  I have given you maintainer access on the website. You need to accept the invite

**Comment by harrisonzhu508** [comment]
Great thanks - got it

**Comment by s-mishra** [comment]
@fvalka I have made a plethora of chnages that will mkae your life easier now once you do a pull on your side.

**Comment by fvalka** [comment]
Hi!

Quick update:
I've got the Dockerimage to work, finally! ;-)

And created a pull request:
https://github.com/ImperialCollegeLondon/covid19model/pull/45

So far it doesn't work on Azure Batch Shipyard yet, but that seems to be 
an issue with the configuration files there which I'm working on.

Good night and all the best
Fabian

**Pull request closed without merging**
