### PR TITLE
Error in plot postprocess_simultation()

### PR DESCRIPTION
**Pull request by abdoulsn**
Hello I've got an error while run the debug syntaxe.
02_at_19.15.42.png) this one was fixed by installing the package.
The second one is in plot case 
Screenshot 2020-05-02 at 19 15 42

### CODE REVIEW

**Comment by s-mishra** [comment]
Hi  Can't see what your PR is about and what problem it is trying to solve.

**Comment by abdoulsn** [comment]
> Hi Can't see what your PR is about and what problem it is trying to solve.

Hello, I updated the post.

**Comment by s-mishra** [comment]
Hi @abdoulsn , if you see this code you are using is not from our code base. Please raise in the repository that has the code you are using. I believe you are using a fork of our project so please talk to them. Also to address this use issues not PR

**Comment by abdoulsn** [comment]
Ha, I did a pr from a forked repo.
Thanks

**Pull request closed without merging**
