### PR TITLE
Create dockerimage.yml

### PR DESCRIPTION
**Pull request by harrisonzhu508**
Initial attempt for docker image with github actions with a dockerimage.yml file.

### CODE REVIEW

**Comment by flaxter** [comment]
This yml will work without docker, right? Shouldn't it be more generally
named?

**Comment by s-mishra** [comment]
@flaxter  we already have yml for conda in the repo now courtsey @cc-a

**Comment by harrisonzhu508** [comment]
We have a Dockerfile already that give the instructions of the image build. I think this will automate the docker build everytime there is a PR or push to master for GitHub

**Comment by cc-a** [comment]
A couple of quick pointers. For GitHub actions to use this file I believe it should be placed in a directory called .github/workflows. One other immediate issue I can see is that you're attempting to run a container before first building the image.

You should be able to test a workflow by changing the execution conditions to dependent on the branch under development rather than master. Then you can swap to master just before merging.

**Comment by ssx** [comment]
@cc-a is correct, needs to go into a `.github/workflows/` directory to take effect.

**Comment by harrisonzhu508** [comment]
will close this leave it others :)

**Pull request closed without merging**
