### PR TITLE
Refactor stan according to issue #33

### LINKED ISSUE #33: improving Stan model efficiency and readability
**Is your feature request related to a problem? Please describe.**

The issue is related to making the Stan code more efficient and readable.

**Describe the solution you'd like**

Ideally, someone codes the suggested changes.  With some feedback, I can code the changes myself, but I didn't want to make a massive PR that the original developers didn't like.  

**Describe alternatives you've considered**

Remove variable `x` because it's not used.  (We're developing a lint mode
that'll flag issues like unused variables.)

----------------------------------------------------------------------

Remove transformed data variable `delta` because it's not used.

----------------------------------------------------------------------

Rename `covariate1`, ..., `covariate6` to `x1`, ..., `x6` because `x` is conventional for covariates and the term "covariate" doesn't convey much information.  Giving these meaningful names would be another possibility.

----------------------------------------------------------------------

Clarify comment on `N2` as to what days of observed data is.  Is it
`max(N)`?

----------------------------------------------------------------------

First, rewrite `Rt[ , m]` for readability:

```
   Rt[ , m] = mu[m] * exp(covariate1[, m] * (-alpha[1])
                           + covariate2[, m] * (-alpha[2])
                           + covariate3[, m] * (-alpha[3])
                           + covariate4[, m] * (-alpha[4])
                           + covariate5[, m] * (-alpha[5])
                           + covariate6[, m] * (-alpha[6]));
```

Then rearrange and move to declare/define style followed by an increment
for the intercept

```
  matrix[N2, M] Rt = exp(-(covariate1 * alpha[1]
                           + covariate2 * alpha[2]
                           + covariate3 * alpha[3]
                           + covariate4 * alpha[4]
                           + covariate5 * alpha[5]
                           + covariate6 * alpha[6]));
  for (m in 1:M) Rt[ , m] *= mu[m];
```

----------------------------------------------------------------------

For readability, I'd sacrifice a bit of speed and use

```
  y_raw ~ exponential(1);  // implies y ~ exponential(1 / tau);
```

instead of

```
  target += -sum(y_raw);  // ...
```

----------------------------------------------------------------------

Keep `tau` itself on unit scale for more efficient adaptation:

```
  parameters {
    real<lower = 0> tau_unit;

  transformed parameters {
    real<lower = 0> tau = tau_unit / 0.03;

  model {
    tau_unit ~ exponential(1);  // implies tau ~ exponential(0.03)
```

----------------------------------------------------------------------

The convolution code can be simplified from

```
  for (m in 1:M) {
    prediction[1:N0, m] = rep_vector(y[m], N0);
    for (i in (N0 + 1):N2) {
      real convolution = 0;
      for (j in 1:(i - 1)) {
        convolution += prediction[j, m] * SI[i - j];
      }
      prediction[i, m] = Rt[i, m] * convolution;
    }
```

to

```
  for (m in 1:M) {
    for (i in 1:N0) {
      prediction[i, m] = y[m];
    }
    for (i in (N0 + 1):N2) {
      real convolution = y[m] * sum(SI[1:(i - 1)]);
      prediction[i, m] = Rt[i, m] * convolution;
    }
```

It's a bit counter-intuitive, but the loop is faster because it doesn't require a new vector copy on the right hand side and loops without autodiff are very fast in Stan.  Given that `preciction[j, m]` was just defined to be `y[m]`, that can be used directly to cut down on memory access in the loop.  

----------------------------------------------------------------------

I assume the centered parameterization

```
mu ~ normal(2.4, kappa)

```

works better than the non-centered one, given that other parameters are non-centered.  Otherwise, this needs to be rewritten in terms of 

```
mu_std ~ std_normal();
```

and

```
mu = 2.4 + kappa * mu_std;
```

----------------------------------------------------------------------

`phi` and `kappa` can be put on unit scales,

```
  transformed parameters {
    real<lower = 0> phi = 5 * phi_std;
    real<lower = 0> kappa = 0.5 * kappa_raw;

  model {
    phi_std ~ std_normal();
    kappa_std ~ std_normal();
```

----------------------------------------------------------------------

The magic number `1e-9` needs doc in the definition of `E_deaths[1, m]`.  `E_deaths` shows up in the negative binomial likelihood as a rate parmeter.  Is it never used because of `EpidemicStart`?  If it's not intended to use, filling unused bits of `E_deaths` with NaN will make sure they raise an error if they're accidentally used somewhere in the target density.

----------------------------------------------------------------------

Put `rep_matrix` in generated data so it's only done once.

```
generated data {
  matrix[N2, M] matrix_1000 = rep_matrix(1000, N2, M);
  matrix[N2, M] matrix_0 = rep_matrix(0, N2, M);

generated quantities {
  matrix[N2, M] lp0 = matrix_1000;
  matrix[N2, M] lp1 = matrix_1000;
  ...
```
----------------------------------------------------------------------

The magic number `1000` in the definition of `matrix_1000` should be documented.

----------------------------------------------------------------------

One way to document constants is to define them as generated data variables with meaningful names.

----------------------------------------------------------------------

The `E_deaths` loop can be pulled up into a function.

```
  functions {
    matrix expected_deaths(matrix prediction, matrix f) {
      int M = rows(prediction);
      int N = cols(prediction);
      matrix[M, N] y;
      for (m in 1:M) {
        y[1, m] = 1e-9;
	for (i in 2:M) {
	  y[2, m] = 0;
	  for (j in 1:(i - 1)) {
	    y[i, m] += prediction[j, m] * f[i - j, m];
          }
        }
      }
      return y;
    }
  }

```

And then the blocks of code can be replaced by

```
  E_deaths = expected_deaths(prediction, f);
  ...
  E_deaths0 = expected_deaths(prediction0, f);
```

Also, `f` is an unusual symbol for a matrix.

----------------------------------------------------------------------

I'm working on getting ragged arrays into the language---sorry we don't
have those yet or the indexing would be much simpler!

### PR DESCRIPTION
**Pull request by harrisonzhu508**
Implemented the code improvements suggested by Bob Carpenter in #33. 

**Problems**
- The function does not seem to work and throws the error
Screenshot from 2020-04-07 23-44-14

so I temporarily used the original loops as a placeholder (so that it works when tested on ubuntu and docker)

- Was thinking of converting the convolution routine into a function too, similar to the expected_deaths, as it is used twice
- I didn't quite get the suggestion
`
mu = 2.4 + kappa * mu_std;
`
why does the centred parameterisation work better?

- @flaxter @s-mishra is it okay to use `y_raw ~ exponential(1);  // implies y ~ exponential(1 / tau);` instead of `  target += -sum(y_raw);  // ...` as suggested? I don't think much speed will be sacrificed.

- More helpful comments should be used in the stan code.

Thanks again to Bob Carpenter for the helpful comments

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Which function isn't working?  

If you can figure out a reusable function for the convolution, that'd be great.   I couldn't see it easily because the use wasn't quite parallel in the two instances.

> why does the centred parameterisation work better?

The centered parameterization will work better when there's enough data to make the posterior roughly normal (it's not just quantity of data, but how low variance it is and how consistent it is with the prior).  Before that, the non-centered parameterization works better.  The reason is that the non-centered parameterization dissociates the hierarchical and lower level parameters in the prior.  There's a discussion in the user's guide around Neal's funnel example.

P.S.  I'd also strongly suggest using spaces arond operators like `+`, `-`, `=` and adding space between `){`.  It maks the code easier to read when symbols aren't all jammed up.

**Comment by harrisonzhu508** [comment]
Thanks for the prompt reply - @bob-carpenter -  the `expected_deaths` function. I've commented it out for the moment in the stan file. The deaths calculation looks a bit messy right now because I was thinking of debugging the function first and using that instead. 

Okay I see - will check out the funnel example! 

And yes I've tried my best to add in the spaces - let me know if there's anything that doesn't look right! :smile:

**Comment by s-mishra** [comment]
@harrisonzhu508  is it ok if we close this? We already got faster and optimzed version from @MansMeg!

**Comment by harrisonzhu508** [comment]
Sure, I'll close this :)

**Pull request closed without merging**
