### PR TITLE
Static website for mobile and desktop

### PR DESCRIPTION
**Pull request by fvalka**
Hey!

I added the website as discussed in issue #11. 

I've extended the R plots in multiple points to produce figures for the website, in both desktop and mobile versions.

You can take a look at the site on my GitHub pages:
https://fvalka.github.io/covid19model/web/index.html

The website itself allows a country selection and shows the three plots from the three-panel, as well as the forecast. 

Currently the whole website has less than 2MB and is responsive, including different images for mobile and desktop. 

I would also like to add an introduction, and some diagnostics plots for the MCMC, Rhat and such.

### CODE REVIEW

**Comment by s-mishra** [comment]
Thanks @fvalka. We are looking into it right now, we might need to tweak website to get more stuff. But this already looks something on lines of whatwe are aiming towards. By the end of the day will revert to you.

**Comment by fvalka** [comment]
Great! I would love to add some more information about the model, the schematic of the model from the paper and such, but that would best be done based upon the original graphics and such. 

If you like we could set up a Zoom call in the afternoon today, I would be available from 16:30 London time. 

All the best and greetings from Vienna
Fabian

**Comment by harrisonzhu508** [comment]
Hi @fvalka  Thank you for your work - the website looks very similar to what we were thinking of!

Any chance you are able to remove the figures from the version control system? Do we also need to add in anything in the CI file - what is the procedure to enable GitHub pages to read the index.html file (I'm presuming it will read the readme file by default) ?

**Comment by fvalka** [comment]
@harrisonzhu508 You're welcome! I'm glad you like it :-) 

I've removed the figures from the branch, and added a recursive directory creation command, before the figures are written, since the directory won't exist anymore. 

Regarding the GitHub actions: I haven't finish any work on this so far, so it's only the website generation in this pull request, but I'm looking into it. 

I would also strongly avoid having a commit in the master branch each day for the page generation. So far it seems like the best route would be to use the gh-pages branch, and write to this one, in this one I would just put the contents of the web/ folder into the root folder, then the index.html is used automatically. 

Alternatively it would maybe be possible, or even necessary to use a second GitHub repo or completely alternative storage for the pages, I'll let you know once I've figured something out :-)

**Comment by s-mishra** [comment]
Hi @fvalka, Thanks again for all of this. Yes, a different branch for gh-pages is what we should aim for. A second Github repo is bit too much. Your contribution is quite welcome and appreciated, just give us some time to sort out a few steps before approving the PR.

**Comment by fvalka** [comment]
You are welcome, I've already found a GitHub action which would solve this, and written the workflow on a feature branch, but so far I can't run any actions on this repo in my own account, doesn't work with the already existing CI workflow either.

**Comment by fvalka** [comment]
I've got it running, but I need to add it to my master branch to run the events, by using the event dispatching API. So there is now already a file in the master branch, but it's a work in progress, but only triggered manually so far :-)

**Comment by s-mishra** [comment]
Thats is cool @fvalka . To make it clear to you, we are taking this on priorrity.

**Comment by fvalka** [comment]
Closing it for now while I'm messing around with my master branch for the GitHub actions workflow. Works 95% so far. I'll open a new one once I'm finished.

**Comment by fvalka** [comment]
Continued in #32

**Pull request closed without merging**
