### PR TITLE
Static website, figure export, GitHub Workflow for running model and creating pages

### PR DESCRIPTION
**Pull request by fvalka**
This is a major pull request, containing multiple changes that add a static website, GitHub workflow for running the model and publishing the website using GitHub pages.

Continuation/Update to pull request #29 and issue #11.  

Preview of the website:
https://fvalka.github.io/covid19model/
Please note that the forecast plots don't work in the DEBUG model and are therefore not shown yet.

I've needed a lot of commits since the workflow could only be tested like this, I'd suggest you squash my commits. 

## Necessary changes to your repo for making it work
- Set GitHub pages to use the gh-pages branch instead of the master branch in the repository settings
- Set up billing for GitHub actions, depending what kind of account this actually is, Team or Pro. Above the free tier I'd expect about 10-20 USD per month, based upon GitHub's pricing at 0.008 USD per minute on a Linux dual core machine.  Above Pro maybe 10 USD. 
- Create a Token which can be used to push to the gh-pages branch and store it as a Secret in the repositories settings under the name GH_PAGES_ACCESS_TOKEN

### Secrets/Token Set-Up
image

### GitHub Pages Setup
image

image

## Execution of the model run/workflow
The workflow can be started in two different ways:
- It is started daily using a schedule at 12:30 UTC, 14:30 CEST. This gives ample room for the sometimes delayed publishing of the data by ECDC
- Manually by executing a GitHub API call, this is described in .github/workflows/run-model-and-publish.yml
- Triggering the workflow only works on the master branch

## Changes to the R base code
- I've added additional plot exports to both the three-panel plots and the forecast. Those are used to export both a mobile and desktop version of each figure. 
- Each figure from the three-panel plots is a separate figure and file. 
- I've removed the Forecast label on the forecast since this was also not shown correctly in the PDF and seems to have been a mistake left in there 
- base.R I've added a mechanism similar to the one used for DEBUG, where either an environment variable can be set or inside the code to use the full number of iterations. The README.md has been changed accordingly. 
- Calculation of N2 based upon 75 + the difference between the ECDC data date and the original reports data date

## Font-workaround
The SVG output in the Docker image creates an invalid font-name "Aerial". I've searched the source code of the R libraries used and found no reference to it. 
- To work around this a new R file has been added: "web-fix-fonts.R", which replaces "Aerial" in the SVG files with a whole font family, making it more robust in addition to fixing this mistake. 

**Changes to the current CI pipeline and Dockerimage**
- I've changed the ENTRYPOINT to a CMD, so that the Dockerimage can also be used correctly with other commands in run
- I've removed the scripts which change the uid and guid and instead used the --user flag of docker run
- The current workflow/CI-pipeline has been adjusted accordingly 

## New workflow
- The new GitHub actions workflow performs a couple of steps for generating the GitHub pages each day:
 - Git clone
 - Build the docker image, as in the CI pipeline
 - Download the newest ECDC data
 - Perform a full model run, set by setting --env FULL=TRUE
 - Apply the font-workaround described above
 - Publish the web subfolder to the gh-pages branch

## Website
The website is built using bootstrap and optimized for mobile and web. 
- Basic UI interaction code is written using just jQuery and one additional JS library to keep it lightweight. 
- The correct tags for accessibility are used (Google Chrome lighthouse audit, performance=99%, accessibility=100%)
- Tested on Edge, Chrome, Firefox, and Chrome on Android. 
- The whole side including all figures for mobile and desktop is less than 2MB in size. 
- Single page
- Loaders/spinners to ensure that even if the network fails the user won't think he switched the country but it didn't load. 

I would also like to add an introduction page to the website, but this would probably best be done in close collaboration, and I'd also need the figures in SVG format and such.

### CODE REVIEW

**Comment by fvalka** [comment]
The model run worked, but the deployment failed since the GitHub token used for authentication is only valid for 60 minutes, but the model run took over 2 hours.

**Comment by harrisonzhu508** [comment]
@fvalka  This is really great, look forward to seeing the readied pull request.

**Comment by fvalka** [comment]
Added a check whether the secret for publishing is correctly set or not. First of all to fail early, but also so that this action doesn't run on everyones account who forks this repo.

**Comment by fvalka** [comment]
@harrisonzhu508 Thank you and I'm really glad you like it! 

I've also just finished a full run in my GitHub actions, took 2h34m, verified the output on GitHub, desktop and mobile. Therefore the pull request is ready!

@s-mishra @flaxter FYI :-) 

All the best, good night from Vienna
Fabian

**Comment by fvalka** [comment]
For reference, the workflow overview on my account:
image

**Comment by fvalka** [comment]
And [Google lighthouse](https://developers.google.com/web/tools/lighthouse) audit of the website:
On mobile:
image

And on desktop:
image

**Comment by harrisonzhu508** [comment]
Wow this is awesome ! One minor thing that I just wanted to comment on, could we change the main title on the index.html file to: Estimating the number of infections and the impact of nonpharmaceutical interventions on COVID-19 in 11 European countries - Imperial College London 

@s-mishra @flaxter what do you think of the title?

And maybe add a note below it:

Last updated (date). The results are updated daily. Any comments or suggestions, please contact the authors of the paper(add link to https://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/report-13-europe-npi-impact/).

Thanks!
Harrison

**Comment by fvalka** [comment]
Changed the title in the title tag, is the one in the navbar okay? "COVID-19 model" the other one would be a bit too long, but it would be possible too, with some changes

**Comment by fvalka** [comment]
I actually also wanted to add the last update date but didn't get around to it yesterday, I would add the latest date in the ECDC data file, then it also shows the correct date if the dataset becomes stale and isn't updated anymore for whatever reason

**Comment by fvalka** [comment]
I have to test the git workflow changes by pushing to the master branch right now again, so please don't merge it right now. 

I've also added a more in depth verification step for the web output, where the latest dates are written for each country, based upon the last entry in the ECDCs dataset for this country.

Additionally those are included in the query string for the file URL, which ensures that images can be cached correctly.

**Comment by fvalka** [comment]
Ready from my side :-)

**Comment by harrisonzhu508** [comment]
@fvalka  Thank you for the hard work Fabian! Just a few final points I promise, could we add our University logo onto the website (on the header or near the header)? Maybe add an acknowledgement at the bottom after the doi link like:

With thanks to the github community contributors for making this website possible.

The link is here:
- https://www.imperial.ac.uk/ImageCropToolT4/imageTool/uploaded-images/White-on-navy--tojpeg_1495792347019_x1.jpg

**Comment by harrisonzhu508** [comment]
@s-mishra  @flaxter any comments? 
https://fvalka.github.io/covid19model/

**Comment by harrisonzhu508** [comment]
Just an update, we have resolved the github actions quota issue @fvalka

**Comment by harrisonzhu508** [comment]
@fvalka  we thought it would also be good to include the table from page 29 onwards here https://www.imperial.ac.uk/media/imperial-college/medicine/sph/ide/gida-fellowships/Imperial-College-COVID19-Europe-estimates-and-NPI-impact-30-03-2020.pdf to a different tab on the website

@fvalka Just to check, is the idea to still trigger via API call? We thought it would make sense to only display results that are verified. We are currently also updating the model so this PR might have to wait another few days if you wouldn't mind!

**Comment by fvalka** [comment]
@harrisonzhu508 I'll add the logo and table of the interventions. I would also love to add the graphic of the interventions, from page 5
image

It might also make sense to include an introduction maybe including this figure, or would you prefer just referencing to the paper?
image

I can remove the cron scheduled trigger from the workflow, might also make more sense. The only big issue is that the manual triggering (described above using the GitHub API) only works for the master branch. So you would either need to create a different GitHub repo (you can merge from the master to there using pull requests) for the actual live website, or do it the other way around of having a second, maybe private GitHub repo where you can do the pre-runs and then do a pull request of the gh-pages from that other repo into the gh-pages of this account for taking it live. 

I'd also say that it's better to manually verify the model output before publishing it each time. Please note that the github pages, even for a private repo will always be public. But verifications could also happen offline. You just need to open the produced index.html.

I've also performed the floor test, of just showing someone (with a background in mathematics) the draft but who hadn't read the paper yet. (What a shame ;-) ), And consider that (n=1) 

And for now the description below the first figure (infections), which I've taken from the paper probably isn't clear enough, taken outside of the context of the paper. 
Maybe we should go with something like:
"Estimated daily number of new infections based upon the modeled daily new deaths and on published estimates of the infection fatality rate, adjusted for each countries age structure, published estimates of the serial interval, and the time dependent reproduction rate R_t. Blue bands are predicted infections, dark blue 50% credible interval (CI), light blue 95% CI. Brown bars are reported infection."

Looking forward to the new model and I'd say anyways that we should take our time to work out these details of the website before releasing it to the wider public.

**Comment by fvalka** [comment]
> @fvalka Thank you for the hard work Fabian! Just a few final points I promise, could we add our University logo onto the website (on the header or near the header)? 

And btw. I've also already borrowed the correct color from the website anyways, so the logo will fit in the header nicely. Similar to the current website. 

> Maybe add an acknowledgement at the bottom after the doi link like:
> With thanks to the github community contributors for making this website possible.

Would you mind if add my name in there? A little self advertisement never hurts since I'm also self employed ;-) and make the github community contributors a link, like:

With thank to the [GitHub community contributors](https://github.com/ImperialCollegeLondon/covid19model/graphs/contributors) and Fabian Valka for making this website possible. 

All the best, Fabian

**Comment by fvalka** [comment]
@harrisonzhu508 I've added the logo, and changed the font to match the logo, also on https://fvalka.github.io/covid19model/ (you maybe just need to Shift+Reload, since the CSS is cached otherwise)

Do you have a version of the table either in CSV, XLS, or even Latex table format for further use?
And also the references, you could also send them in Bibtex format. 

I would like to add the information about the interventions on each countries page, and maybe also include an overview page of all measures in detail.

**Comment by fvalka** [comment]
I've switched to vue js since it kind of starts to outgrow the just plain javascript approach, and started to add the timelines, for now the draft includes the timeline for Austria, I'm also working on adding an overview page with the all the interventions

**Comment by s-mishra** [comment]
Thanks a ton @fvalka. We should have a call to get this thing sorted as you have done a lot and there is a need for a manual update rather than the full auto-update (thankfully you also think same). I would like us to have discussion about it and then proceed. @harrisonzhu508 and @fvalka lets discuss this sometime today after 2 pm London time.

**Comment by fvalka** [comment]
@s-mishra You are welcome! Sounds good. 3pm London time, or later, would work for me, I've just sent you an email with a meeting invite and my phone number. Looking forward to talking to you :-)

**Comment by harrisonzhu508** [comment]
@s-mishra  great would be free to chat later. Could you forward me the invite? Thanks.

**Comment by fvalka** [comment]
@harrisonzhu508 Sounds good. I've already had a quick call with @s-mishra and am working on splitting up the repos and cleaning up the changes to this repo. 

Therefore I'll also close this pull request, since I've created a new branch in my fork for a clean commit history for which I'll open a new pull request.

**Pull request closed without merging**
